"""Rank - The official Python SDK for the Rank API.

Usage:
    import rank

    # Synchronous
    client = rank.Rank(api_key="rk_...")
    pentests = client.pentests.list()

    # Asynchronous
    async_client = rank.AsyncRank(api_key="rk_...")
    pentests = await async_client.pentests.list()

    # Streaming (AI chat)
    with client.ai.chat.stream(agent_id=1, user_prompt="Scan target") as stream:
        for event in stream:
            print(event.content, end="")
"""

from __future__ import annotations

from ._client import AsyncRank, Rank
from ._constants import PACKAGE_VERSION
from ._exceptions import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    PermissionDeniedError,
    RankError,
    RateLimitError,
    SignatureVerificationError,
    UnprocessableEntityError,
)
from ._streaming import AgentEvent, AsyncStream, ServerSentEvent, Stream
from ._utils._transform import NOT_GIVEN
from .types import (
    # Agent
    Agent,
    # Pentest
    AgentAssignment,
    AgentCloneResponse,
    AgentCreateResponse,
    AgentDeleteResponse,
    AgentGroupedResponse,
    AgentListResponse,
    AgentMcp,
    AgentMcpListResponse,
    AgentTool,
    AgentToolListResponse,
    AgentUpdateResponse,
    # AI Models
    AIModel,
    # Auth
    ApiToken,
    ApiTokenCreateResponse,
    ApiTokenLimits,
    ApiTokenListResponse,
    ApiTokenTeam,
    # Control / RoE
    Approval,
    # Catalogs
    ApprovalClass,
    ApprovalClassListResponse,
    ApprovalListResponse,
    AssetCreateResponse,
    AssetListResponse,
    AssignAgentsResponse,
    AssignMcpsResponse,
    # Chat
    AssignOperationsResponse,
    AssignToolsResponse,
    AssignVulnerabilitiesResponse,
    AttackTechnique,
    AttackTechniqueListResponse,
    # Evidence
    AuditChainResponse,
    AuditChainVerifyResponse,
    AvailablePermissionsResponse,
    AvailableTeam,
    AvailableToolListResponse,
    BillingInvoice,
    BillingInvoicesResponse,
    BillingStatusResponse,
    BillingSubscription,
    # Billing
    BillingTrialStatusResponse,
    BulkStatusError,
    BulkStatusResponse,
    CatalogField,
    CatalogFieldOption,
    Chat,
    ChatArchiveResponse,
    ChatListResponse,
    # AI
    ChatMessage,
    ChatMineResponse,
    ChatNameResponse,
    ChatOperation,
    ChatOperationListResponse,
    ChatSharedResponse,
    ChatShareResponse,
    ChatUnshareResponse,
    ChatVulnerability,
    ChatVulnerabilityListResponse,
    CweEntry,
    CweListResponse,
    DeactivateAgentsResponse,
    DefaultAgentPhase,
    DefaultAgentsResponse,
    EngagementRoe,
    # Shared
    ErrorDetail,
    EscalationContact,
    EvidenceArtifact,
    EvidenceArtifactDetail,
    EvidenceArtifactListResponse,
    EvidenceFile,
    EvidenceFileDeleteResponse,
    EvidenceFileListResponse,
    EvidenceFileUploadResponse,
    EvidenceManifest,
    EvidencesResponse,
    FindingProvenance,
    FinishVulnSummary,
    GenerateReportResponse,
    GlobalVulnerabilitySummaryResponse,
    # Integrations
    Integration,
    IntegrationCreateResponse,
    IntegrationLink,
    IntegrationLinkListResponse,
    IntegrationListResponse,
    IntegrationProvider,
    IntegrationProviderListResponse,
    IntegrationShowResponse,
    IntegrationSyncResult,
    IntegrationTestResponse,
    # Team
    InvitationAcceptResponse,
    InvitationCreateResponse,
    InvitationDetail,
    InvitationListPagination,
    InvitationListResponse,
    InvitationStats,
    # Reports
    IssuedReport,
    IssuedReportDownload,
    IssuedReportListResponse,
    # Tickets
    JiraAttachment,
    JiraComment,
    KillResponse,
    # MCP Servers
    McpServer,
    McpServerCreateResponse,
    McpServerDeleteResponse,
    McpServerListResponse,
    MemberListResponse,
    MessageResponse,
    Methodology,
    MethodologyListResponse,
    ModelAssignResponse,
    ModelListResponse,
    OnDemandToggleResponse,
    # Operation logs
    OperationAgentInfo,
    OperationEvidence,
    OperationEvidenceVuln,
    OperationLog,
    OperationLogListResponse,
    OperationModelInfo,
    OperationPentestInfo,
    PaginatedResponse,
    PaginationInfo,
    PaginationMeta,
    Pentest,
    PentestAgent,
    PentestAgentListResponse,
    PentestAsset,
    PentestCancelResponse,
    PentestComment,
    PentestCommentCreateResponse,
    PentestCommentListResponse,
    Pentester,
    PentestFinishResponse,
    PentestLimits,
    PentestListResponse,
    PentestTeam,
    Permission,
    PermissionListResponse,
    Phase,
    PhaseListResponse,
    ProcessedVulnerability,
    ProcessVulnerabilitiesResponse,
    ProfileUpdateResponse,
    QualityGateFailure,
    QualityGatePentestResult,
    QualityGateResponse,
    QualityGateSnapshot,
    RankModel,
    # Policy
    RemediationPolicy,
    RemediationPolicyResponse,
    RemoveMcpResponse,
    RemoveToolResponse,
    RemoveVulnerabilityResponse,
    ReportProfile,
    ReportProfileFieldsResponse,
    ReportProfileResponse,
    ReportSettingsResponse,
    RetentionPolicy,
    # Retest
    RetestRun,
    RetestRunListResponse,
    RetestSummary,
    RiskScore,
    RoeResponse,
    RoeTimeWindow,
    RoeVersionSummary,
    RoleListResponse,
    ScheduledPentest,
    ScheduledPentestCancelResponse,
    # Scheduled pentests
    ScheduledPentestInfo,
    ScheduledPentestListResponse,
    Session,
    SessionListResponse,
    SessionUserData,
    Subscription,
    SuccessResponse,
    Team,
    TeamAgentCreateResponse,
    TeamAgentDeleteResponse,
    TeamAgentDetail,
    TeamAgentGroup,
    TeamAgentItem,
    TeamAgentListResponse,
    TeamInvitation,
    TeamListResponse,
    TeamMember,
    TeamRole,
    Ticket,
    TicketAddAttachmentResponse,
    TicketAttachment,
    TicketComment,
    TicketCreateResponse,
    TicketListResponse,
    Tier,
    TierCharacteristic,
    TierDetail,
    TierListResponse,
    Trial,
    UnassignAgentResponse,
    UpdateEmailResponse,
    UpdateUsernameResponse,
    UsageBillingPeriod,
    UsageBudget,
    UsageDailyEntry,
    UsageDailyResponse,
    UsageHistoryItem,
    UsageHistoryResponse,
    UsageHourlyEntry,
    UsageMemberDetailResponse,
    UsageMemberInfo,
    UsageMembersResponse,
    UsageMemberSummary,
    UsageModelBreakdown,
    UsageOnDemand,
    UsageSummaryResponse,
    UsageTeamInfo,
    UsageTeamTier,
    UsageTotals,
    User,
    UserInvitation,
    UserInvitationListResponse,
    UserTeam,
    UserTeamRole,
    ValidationMetricsClass,
    ValidationMetricsResponse,
    Vulnerability,
    VulnerabilityAcceptRiskResponse,
    VulnerabilityAssignResponse,
    VulnerabilityComment,
    VulnerabilityCommentCreateResponse,
    VulnerabilityCommentDeleteResponse,
    VulnerabilityCommentListResponse,
    VulnerabilityCommentUpdateResponse,
    VulnerabilityEvidenceResponse,
    VulnerabilityExportFile,
    VulnerabilityExportResponse,
    VulnerabilityFalsePositiveResponse,
    VulnerabilityHistoryItem,
    VulnerabilityHistoryResponse,
    VulnerabilityListItem,
    VulnerabilityListResponse,
    VulnerabilityPriorityChangeResponse,
    VulnerabilityQualityGateResponse,
    VulnerabilityReopenResponse,
    VulnerabilityResolveResponse,
    VulnerabilityReviewResponse,
    VulnerabilityStatusChangeResponse,
    VulnerabilitySummary,
    VulnerabilityUnassignResponse,
    VulnProcessingStatus,
    VulnSeveritySummary,
    Webhook,
    WebhookCreateResponse,
    WebhookDeleteResponse,
    # Tenant webhooks
    WebhookDelivery,
    WebhookDeliveryListResponse,
    WebhookListResponse,
    WebhookSubscription,
    WebhookSubscriptionCreateResponse,
    WebhookSubscriptionListResponse,
    WebhookSubscriptionShowResponse,
    WebhookTestResponse,
)
from .webhooks import verify_signature

__version__ = PACKAGE_VERSION

__all__ = [
    # Clients
    "Rank",
    "AsyncRank",
    # Version
    "__version__",
    # Exceptions
    "RankError",
    "APIError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "ConflictError",
    "UnprocessableEntityError",
    "RateLimitError",
    "InternalServerError",
    "APIConnectionError",
    "APITimeoutError",
    "SignatureVerificationError",
    # Streaming
    "Stream",
    "AsyncStream",
    "ServerSentEvent",
    "AgentEvent",
    # Utilities
    "NOT_GIVEN",
    "verify_signature",
    # AI types
    "ChatMessage",
    "ChatNameResponse",
    # Agent types
    "Agent",
    "AgentCreateResponse",
    "AgentUpdateResponse",
    "AgentCloneResponse",
    "AgentDeleteResponse",
    "TeamAgentGroup",
    "AgentListResponse",
    "AgentGroupedResponse",
    "AgentTool",
    "AgentToolListResponse",
    "AvailableToolListResponse",
    "AssignToolsResponse",
    "RemoveToolResponse",
    "AgentMcp",
    "AgentMcpListResponse",
    "AssignMcpsResponse",
    "RemoveMcpResponse",
    # AI Model types
    "AIModel",
    "ModelListResponse",
    "ModelAssignResponse",
    # MCP Server types
    "McpServer",
    "McpServerListResponse",
    "McpServerCreateResponse",
    "McpServerDeleteResponse",
    # Chat types
    "Chat",
    "ChatListResponse",
    "ChatMineResponse",
    "ChatSharedResponse",
    "ChatOperation",
    "ChatOperationListResponse",
    "AssignOperationsResponse",
    "ChatVulnerability",
    "ChatVulnerabilityListResponse",
    "AssignVulnerabilitiesResponse",
    "RemoveVulnerabilityResponse",
    "ChatShareResponse",
    "ChatUnshareResponse",
    "ChatArchiveResponse",
    # Operation log types
    "OperationModelInfo",
    "OperationAgentInfo",
    "OperationPentestInfo",
    "OperationLog",
    "OperationLogListResponse",
    # Shared types
    "RankModel",
    "PaginatedResponse",
    "PaginationMeta",
    "PaginationInfo",
    "Permission",
    "PermissionListResponse",
    "MessageResponse",
    "SuccessResponse",
    "ErrorDetail",
    # Auth types
    "User",
    "Tier",
    "TierCharacteristic",
    "TierDetail",
    "TierListResponse",
    "Trial",
    "Subscription",
    "UserTeam",
    "UserTeamRole",
    "Session",
    "SessionListResponse",
    "SessionUserData",
    "ApiToken",
    "ApiTokenTeam",
    "AvailableTeam",
    "ApiTokenLimits",
    "ApiTokenListResponse",
    "ApiTokenCreateResponse",
    "AvailablePermissionsResponse",
    "ProfileUpdateResponse",
    "UpdateEmailResponse",
    "UpdateUsernameResponse",
    # Billing types
    "BillingTrialStatusResponse",
    "BillingSubscription",
    "BillingStatusResponse",
    "BillingInvoice",
    "BillingInvoicesResponse",
    # Pentest types
    "Pentester",
    "PentestTeam",
    "PentestAsset",
    "RiskScore",
    "Pentest",
    "PentestListResponse",
    "FinishVulnSummary",
    "PentestFinishResponse",
    "PentestLimits",
    "QualityGateFailure",
    "QualityGatePentestResult",
    "QualityGateResponse",
    "QualityGateSnapshot",
    "AssetListResponse",
    "AssetCreateResponse",
    "PentestComment",
    "PentestCommentListResponse",
    "PentestCommentCreateResponse",
    "Webhook",
    "WebhookListResponse",
    "WebhookCreateResponse",
    "WebhookDeleteResponse",
    "PentestAgent",
    "PentestAgentListResponse",
    "AgentAssignment",
    "AssignAgentsResponse",
    "UnassignAgentResponse",
    "DeactivateAgentsResponse",
    "DefaultAgentPhase",
    "DefaultAgentsResponse",
    "OperationEvidenceVuln",
    "OperationEvidence",
    "EvidencesResponse",
    "VulnerabilityEvidenceResponse",
    "EvidenceFile",
    "EvidenceFileListResponse",
    "EvidenceFileUploadResponse",
    "EvidenceFileDeleteResponse",
    # Phase types
    "Phase",
    "PhaseListResponse",
    # Methodology types
    "Methodology",
    "MethodologyListResponse",
    # Scheduled pentest types
    "ScheduledPentestInfo",
    "ScheduledPentest",
    "ScheduledPentestListResponse",
    "ScheduledPentestCancelResponse",
    # Global vulnerability summary
    "GlobalVulnerabilitySummaryResponse",
    # Vulnerability types
    "Vulnerability",
    "VulnerabilityListItem",
    "VulnerabilityListResponse",
    "VulnerabilitySummary",
    "VulnerabilityExportResponse",
    "VulnerabilityExportFile",
    "VulnerabilityQualityGateResponse",
    "VulnerabilityResolveResponse",
    "VulnerabilityReopenResponse",
    "VulnerabilityFalsePositiveResponse",
    "VulnerabilityAcceptRiskResponse",
    "VulnerabilityStatusChangeResponse",
    "VulnerabilityPriorityChangeResponse",
    "VulnerabilityAssignResponse",
    "VulnerabilityUnassignResponse",
    "BulkStatusError",
    "BulkStatusResponse",
    "VulnerabilityComment",
    "VulnerabilityCommentListResponse",
    "VulnerabilityCommentCreateResponse",
    "VulnerabilityCommentUpdateResponse",
    "VulnerabilityCommentDeleteResponse",
    "VulnerabilityHistoryItem",
    "VulnerabilityHistoryResponse",
    "PentestCancelResponse",
    "ProcessedVulnerability",
    "ProcessVulnerabilitiesResponse",
    "VulnSeveritySummary",
    "VulnProcessingStatus",
    "GenerateReportResponse",
    # Team types
    "Team",
    "TeamListResponse",
    "TeamMember",
    "MemberListResponse",
    "TeamRole",
    "RoleListResponse",
    "InvitationAcceptResponse",
    "InvitationCreateResponse",
    "InvitationDetail",
    "InvitationStats",
    "TeamInvitation",
    "InvitationListPagination",
    "InvitationListResponse",
    "UserInvitation",
    "UserInvitationListResponse",
    "TeamAgentItem",
    "TeamAgentDetail",
    "TeamAgentListResponse",
    "TeamAgentCreateResponse",
    "TeamAgentDeleteResponse",
    "UsageBillingPeriod",
    "UsageTeamTier",
    "UsageTeamInfo",
    "UsageOnDemand",
    "UsageBudget",
    "UsageTotals",
    "UsageModelBreakdown",
    "UsageSummaryResponse",
    "UsageDailyEntry",
    "UsageHourlyEntry",
    "UsageDailyResponse",
    "UsageMemberSummary",
    "UsageMembersResponse",
    "UsageMemberInfo",
    "UsageMemberDetailResponse",
    "UsageHistoryItem",
    "UsageHistoryResponse",
    "OnDemandToggleResponse",
    # Ticket types
    "JiraAttachment",
    "JiraComment",
    "Ticket",
    "TicketAddAttachmentResponse",
    "TicketComment",
    "TicketAttachment",
    "TicketListResponse",
    "TicketCreateResponse",
    # Catalogs
    "CweEntry",
    "CweListResponse",
    "AttackTechnique",
    "AttackTechniqueListResponse",
    "ApprovalClass",
    "ApprovalClassListResponse",
    "CatalogFieldOption",
    "CatalogField",
    "ReportProfileFieldsResponse",
    "ValidationMetricsClass",
    "ValidationMetricsResponse",
    # Control / RoE
    "RoeTimeWindow",
    "EscalationContact",
    "EngagementRoe",
    "RoeVersionSummary",
    "RoeResponse",
    "KillResponse",
    "Approval",
    "ApprovalListResponse",
    # Evidence
    "EvidenceArtifact",
    "EvidenceArtifactListResponse",
    "EvidenceArtifactDetail",
    "EvidenceManifest",
    "AuditChainResponse",
    "AuditChainVerifyResponse",
    "FindingProvenance",
    "RetentionPolicy",
    # Reports
    "ReportProfile",
    "ReportProfileResponse",
    "ReportSettingsResponse",
    "IssuedReport",
    "IssuedReportListResponse",
    "IssuedReportDownload",
    # Retest
    "RetestSummary",
    "RetestRun",
    "RetestRunListResponse",
    "VulnerabilityReviewResponse",
    # Tenant webhooks
    "WebhookSubscription",
    "WebhookSubscriptionListResponse",
    "WebhookSubscriptionCreateResponse",
    "WebhookSubscriptionShowResponse",
    "WebhookDelivery",
    "WebhookDeliveryListResponse",
    "WebhookTestResponse",
    # Integrations
    "IntegrationProvider",
    "IntegrationProviderListResponse",
    "Integration",
    "IntegrationListResponse",
    "IntegrationCreateResponse",
    "IntegrationShowResponse",
    "IntegrationSyncResult",
    "IntegrationTestResponse",
    "IntegrationLink",
    "IntegrationLinkListResponse",
    # Policy
    "RemediationPolicy",
    "RemediationPolicyResponse",
]
