"""Rank - The official Python SDK for the Rank API.

Usage:
    import rank

    # Synchronous
    client = rank.Rank(api_key="rk_...")
    pentests = client.pentests.list()

    # Asynchronous
    async_client = rank.AsyncRank(api_key="rk_...")
    pentests = await async_client.pentests.list()

    # Streaming (AI chat)
    with client.ai.chat.stream(agent_id=1, user_prompt="Scan target") as stream:
        for event in stream:
            print(event.content, end="")
"""

from __future__ import annotations

from ._client import AsyncRank, Rank
from ._constants import PACKAGE_VERSION
from ._exceptions import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    PermissionDeniedError,
    RankError,
    RateLimitError,
    UnprocessableEntityError,
)
from ._streaming import AsyncStream, ServerSentEvent, Stream
from ._utils._transform import NOT_GIVEN
from .types import (
    # AI
    ChatMessage,
    ChatNameResponse,
    # Agent
    Agent,
    AgentCloneResponse,
    AgentCreateResponse,
    AgentDeleteResponse,
    AgentGroupedResponse,
    AgentListResponse,
    AgentMcp,
    AgentMcpListResponse,
    AgentTool,
    AgentToolListResponse,
    AgentUpdateResponse,
    AssignMcpsResponse,
    AssignToolsResponse,
    AvailableToolListResponse,
    RemoveMcpResponse,
    RemoveToolResponse,
    TeamAgentGroup,
    # AI Models
    AIModel,
    ModelListResponse,
    ModelAssignResponse,
    # MCP Servers
    McpServer,
    McpServerListResponse,
    McpServerCreateResponse,
    McpServerDeleteResponse,
    # Chat
    AssignOperationsResponse,
    Chat,
    ChatArchiveResponse,
    ChatListResponse,
    ChatMineResponse,
    ChatOperation,
    ChatOperationListResponse,
    ChatSharedResponse,
    ChatShareResponse,
    ChatUnshareResponse,
    # Operation logs
    OperationAgentInfo,
    OperationLog,
    OperationLogListResponse,
    OperationModelInfo,
    OperationPentestInfo,
    # Shared
    ErrorDetail,
    MessageResponse,
    PaginatedResponse,
    PaginationInfo,
    PaginationMeta,
    Permission,
    PermissionListResponse,
    RankModel,
    SuccessResponse,
    # Auth
    ApiToken,
    ApiTokenCreateResponse,
    ApiTokenLimits,
    ApiTokenListResponse,
    ApiTokenTeam,
    AvailablePermissionsResponse,
    AvailableTeam,
    ProfileUpdateResponse,
    Session,
    SessionListResponse,
    SessionUserData,
    Subscription,
    Tier,
    TierCharacteristic,
    TierDetail,
    TierListResponse,
    Trial,
    UpdateEmailResponse,
    UpdateUsernameResponse,
    User,
    UserTeam,
    UserTeamRole,
    # Billing
    BillingTrialStatusResponse,
    BillingSubscription,
    BillingStatusResponse,
    BillingInvoice,
    BillingInvoicesResponse,
    # Pentest
    AgentAssignment,
    AssetCreateResponse,
    AssetListResponse,
    AssignAgentsResponse,
    BulkStatusError,
    BulkStatusResponse,
    DeactivateAgentsResponse,
    DefaultAgentPhase,
    DefaultAgentsResponse,
    EvidenceFile,
    EvidenceFileDeleteResponse,
    EvidenceFileListResponse,
    EvidenceFileUploadResponse,
    EvidencesResponse,
    FinishVulnSummary,
    GenerateReportResponse,
    GlobalVulnerabilitySummaryResponse,
    Methodology,
    MethodologyListResponse,
    OperationEvidence,
    OperationEvidenceVuln,
    Pentest,
    PentestAgent,
    PentestAgentListResponse,
    PentestAsset,
    PentestCancelResponse,
    PentestComment,
    PentestCommentCreateResponse,
    PentestCommentListResponse,
    PentestFinishResponse,
    PentestListResponse,
    PentestTeam,
    Pentester,
    Phase,
    PhaseListResponse,
    ProcessVulnerabilitiesResponse,
    ProcessedVulnerability,
    QualityGateFailure,
    QualityGatePentestResult,
    QualityGateResponse,
    RiskScore,
    UnassignAgentResponse,
    Vulnerability,
    VulnerabilityAcceptRiskResponse,
    VulnerabilityAssignResponse,
    VulnerabilityComment,
    VulnerabilityCommentCreateResponse,
    VulnerabilityCommentDeleteResponse,
    VulnerabilityCommentListResponse,
    VulnerabilityCommentUpdateResponse,
    VulnerabilityEvidenceResponse,
    VulnerabilityExportResponse,
    VulnerabilityFalsePositiveResponse,
    VulnerabilityHistoryItem,
    VulnerabilityHistoryResponse,
    VulnerabilityListItem,
    VulnerabilityListResponse,
    VulnerabilityPriorityChangeResponse,
    VulnerabilityQualityGateResponse,
    VulnerabilityReopenResponse,
    VulnerabilityResolveResponse,
    VulnerabilityStatusChangeResponse,
    VulnerabilitySummary,
    VulnerabilityUnassignResponse,
    Webhook,
    WebhookCreateResponse,
    WebhookDeleteResponse,
    WebhookListResponse,
    # Scheduled pentests
    ScheduledPentestInfo,
    ScheduledPentest,
    ScheduledPentestListResponse,
    ScheduledPentestCancelResponse,
    # Team
    InvitationAcceptResponse,
    InvitationCreateResponse,
    InvitationDetail,
    InvitationListPagination,
    InvitationListResponse,
    InvitationStats,
    MemberListResponse,
    OnDemandToggleResponse,
    RoleListResponse,
    Team,
    TeamAgentCreateResponse,
    TeamAgentDeleteResponse,
    TeamAgentDetail,
    TeamAgentItem,
    TeamAgentListResponse,
    TeamInvitation,
    TeamListResponse,
    TeamMember,
    TeamRole,
    UsageBillingPeriod,
    UsageBudget,
    UsageDailyEntry,
    UsageDailyResponse,
    UsageHistoryItem,
    UsageHistoryResponse,
    UsageHourlyEntry,
    UsageMemberDetailResponse,
    UsageMemberInfo,
    UsageMemberSummary,
    UsageMembersResponse,
    UsageModelBreakdown,
    UsageOnDemand,
    UsageSummaryResponse,
    UsageTeamInfo,
    UsageTeamTier,
    UserInvitation,
    UserInvitationListResponse,
    UsageTotals,
    # Tickets
    JiraAttachment,
    JiraComment,
    Ticket,
    TicketAddAttachmentResponse,
    TicketComment,
    TicketAttachment,
    TicketListResponse,
    TicketCreateResponse,
)

__version__ = PACKAGE_VERSION

__all__ = [
    # Clients
    "Rank",
    "AsyncRank",
    # Version
    "__version__",
    # Exceptions
    "RankError",
    "APIError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "ConflictError",
    "UnprocessableEntityError",
    "RateLimitError",
    "InternalServerError",
    "APIConnectionError",
    "APITimeoutError",
    # Streaming
    "Stream",
    "AsyncStream",
    "ServerSentEvent",
    # Utilities
    "NOT_GIVEN",
    # AI types
    "ChatMessage",
    "ChatNameResponse",
    # Agent types
    "Agent",
    "AgentCreateResponse",
    "AgentUpdateResponse",
    "AgentCloneResponse",
    "AgentDeleteResponse",
    "TeamAgentGroup",
    "AgentListResponse",
    "AgentGroupedResponse",
    "AgentTool",
    "AgentToolListResponse",
    "AvailableToolListResponse",
    "AssignToolsResponse",
    "RemoveToolResponse",
    "AgentMcp",
    "AgentMcpListResponse",
    "AssignMcpsResponse",
    "RemoveMcpResponse",
    # AI Model types
    "AIModel",
    "ModelListResponse",
    "ModelAssignResponse",
    # MCP Server types
    "McpServer",
    "McpServerListResponse",
    "McpServerCreateResponse",
    "McpServerDeleteResponse",
    # Chat types
    "Chat",
    "ChatListResponse",
    "ChatMineResponse",
    "ChatSharedResponse",
    "ChatOperation",
    "ChatOperationListResponse",
    "AssignOperationsResponse",
    "ChatShareResponse",
    "ChatUnshareResponse",
    "ChatArchiveResponse",
    # Operation log types
    "OperationModelInfo",
    "OperationAgentInfo",
    "OperationPentestInfo",
    "OperationLog",
    "OperationLogListResponse",
    # Shared types
    "RankModel",
    "PaginatedResponse",
    "PaginationMeta",
    "PaginationInfo",
    "Permission",
    "PermissionListResponse",
    "MessageResponse",
    "SuccessResponse",
    "ErrorDetail",
    # Auth types
    "User",
    "Tier",
    "TierCharacteristic",
    "TierDetail",
    "TierListResponse",
    "Trial",
    "Subscription",
    "UserTeam",
    "UserTeamRole",
    "Session",
    "SessionListResponse",
    "SessionUserData",
    "ApiToken",
    "ApiTokenTeam",
    "AvailableTeam",
    "ApiTokenLimits",
    "ApiTokenListResponse",
    "ApiTokenCreateResponse",
    "AvailablePermissionsResponse",
    "ProfileUpdateResponse",
    "UpdateEmailResponse",
    "UpdateUsernameResponse",
    # Billing types
    "BillingTrialStatusResponse",
    "BillingSubscription",
    "BillingStatusResponse",
    "BillingInvoice",
    "BillingInvoicesResponse",
    # Pentest types
    "Pentester",
    "PentestTeam",
    "PentestAsset",
    "RiskScore",
    "Pentest",
    "PentestListResponse",
    "FinishVulnSummary",
    "PentestFinishResponse",
    "QualityGateFailure",
    "QualityGatePentestResult",
    "QualityGateResponse",
    "AssetListResponse",
    "AssetCreateResponse",
    "PentestComment",
    "PentestCommentListResponse",
    "PentestCommentCreateResponse",
    "Webhook",
    "WebhookListResponse",
    "WebhookCreateResponse",
    "WebhookDeleteResponse",
    "PentestAgent",
    "PentestAgentListResponse",
    "AgentAssignment",
    "AssignAgentsResponse",
    "UnassignAgentResponse",
    "DeactivateAgentsResponse",
    "DefaultAgentPhase",
    "DefaultAgentsResponse",
    "OperationEvidenceVuln",
    "OperationEvidence",
    "EvidencesResponse",
    "VulnerabilityEvidenceResponse",
    "EvidenceFile",
    "EvidenceFileListResponse",
    "EvidenceFileUploadResponse",
    "EvidenceFileDeleteResponse",
    # Phase types
    "Phase",
    "PhaseListResponse",
    # Methodology types
    "Methodology",
    "MethodologyListResponse",
    # Scheduled pentest types
    "ScheduledPentestInfo",
    "ScheduledPentest",
    "ScheduledPentestListResponse",
    "ScheduledPentestCancelResponse",
    # Global vulnerability summary
    "GlobalVulnerabilitySummaryResponse",
    # Vulnerability types
    "Vulnerability",
    "VulnerabilityListItem",
    "VulnerabilityListResponse",
    "VulnerabilitySummary",
    "VulnerabilityExportResponse",
    "VulnerabilityQualityGateResponse",
    "VulnerabilityResolveResponse",
    "VulnerabilityReopenResponse",
    "VulnerabilityFalsePositiveResponse",
    "VulnerabilityAcceptRiskResponse",
    "VulnerabilityStatusChangeResponse",
    "VulnerabilityPriorityChangeResponse",
    "VulnerabilityAssignResponse",
    "VulnerabilityUnassignResponse",
    "BulkStatusError",
    "BulkStatusResponse",
    "VulnerabilityComment",
    "VulnerabilityCommentListResponse",
    "VulnerabilityCommentCreateResponse",
    "VulnerabilityCommentUpdateResponse",
    "VulnerabilityCommentDeleteResponse",
    "VulnerabilityHistoryItem",
    "VulnerabilityHistoryResponse",
    "PentestCancelResponse",
    "ProcessedVulnerability",
    "ProcessVulnerabilitiesResponse",
    "GenerateReportResponse",
    # Team types
    "Team",
    "TeamListResponse",
    "TeamMember",
    "MemberListResponse",
    "TeamRole",
    "RoleListResponse",
    "InvitationAcceptResponse",
    "InvitationCreateResponse",
    "InvitationDetail",
    "InvitationStats",
    "TeamInvitation",
    "InvitationListPagination",
    "InvitationListResponse",
    "UserInvitation",
    "UserInvitationListResponse",
    "TeamAgentItem",
    "TeamAgentDetail",
    "TeamAgentListResponse",
    "TeamAgentCreateResponse",
    "TeamAgentDeleteResponse",
    "UsageBillingPeriod",
    "UsageTeamTier",
    "UsageTeamInfo",
    "UsageOnDemand",
    "UsageBudget",
    "UsageTotals",
    "UsageModelBreakdown",
    "UsageSummaryResponse",
    "UsageDailyEntry",
    "UsageHourlyEntry",
    "UsageDailyResponse",
    "UsageMemberSummary",
    "UsageMembersResponse",
    "UsageMemberInfo",
    "UsageMemberDetailResponse",
    "UsageHistoryItem",
    "UsageHistoryResponse",
    "OnDemandToggleResponse",
    # Ticket types
    "JiraAttachment",
    "JiraComment",
    "Ticket",
    "TicketAddAttachmentResponse",
    "TicketComment",
    "TicketAttachment",
    "TicketListResponse",
    "TicketCreateResponse",
]
