"""Rank - The official Python SDK for the Rank API.

Usage:
    import rank

    # Synchronous
    client = rank.Rank(api_key="rk_...")
    pentests = client.pentests.list()

    # Asynchronous
    async_client = rank.AsyncRank(api_key="rk_...")
    pentests = await async_client.pentests.list()

    # Streaming (AI chat)
    with client.ai.chat.stream(agent_id=1, user_prompt="Scan target") as stream:
        for event in stream:
            print(event.content, end="")
"""

from __future__ import annotations

from ._client import AsyncRank, Rank
from ._constants import PACKAGE_VERSION
from ._exceptions import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    PermissionDeniedError,
    RankError,
    RateLimitError,
    UnprocessableEntityError,
)
from ._streaming import AsyncStream, ServerSentEvent, Stream
from ._utils._transform import NOT_GIVEN
from .types import (
    AgentAssignment,
    ApiToken,
    ApiTokenCreateResponse,
    ApiTokenLimits,
    ApiTokenListResponse,
    ApiTokenTeam,
    AssetCreateResponse,
    AssetListResponse,
    AssignAgentsResponse,
    AvailablePermissionsResponse,
    AvailableTeam,
    BulkStatusError,
    BulkStatusResponse,
    DeactivateAgentsResponse,
    DefaultAgentPhase,
    DefaultAgentsResponse,
    ErrorDetail,
    EvidenceFile,
    EvidenceFileDeleteResponse,
    EvidenceFileListResponse,
    EvidenceFileUploadResponse,
    EvidencesResponse,
    FinishVulnSummary,
    GenerateReportResponse,
    MessageResponse,
    OperationEvidence,
    OperationEvidenceVuln,
    PaginatedResponse,
    PaginationInfo,
    PaginationMeta,
    Pentest,
    PentestAgent,
    PentestAgentListResponse,
    PentestAsset,
    PentestCancelResponse,
    PentestComment,
    PentestCommentCreateResponse,
    PentestCommentListResponse,
    PentestFinishResponse,
    PentestListResponse,
    PentestTeam,
    Pentester,
    Permission,
    ProcessVulnerabilitiesResponse,
    ProcessedVulnerability,
    ProfileUpdateResponse,
    QualityGateFailure,
    QualityGatePentestResult,
    QualityGateResponse,
    RankModel,
    RiskScore,
    Session,
    SessionListResponse,
    SessionUserData,
    Subscription,
    SuccessResponse,
    Tier,
    Trial,
    UnassignAgentResponse,
    UpdateEmailResponse,
    UpdateUsernameResponse,
    User,
    UserTeam,
    UserTeamRole,
    Vulnerability,
    VulnerabilityAcceptRiskResponse,
    VulnerabilityAssignResponse,
    VulnerabilityComment,
    VulnerabilityCommentCreateResponse,
    VulnerabilityCommentDeleteResponse,
    VulnerabilityCommentListResponse,
    VulnerabilityCommentUpdateResponse,
    VulnerabilityEvidenceResponse,
    VulnerabilityExportResponse,
    VulnerabilityFalsePositiveResponse,
    VulnerabilityHistoryItem,
    VulnerabilityHistoryResponse,
    VulnerabilityListItem,
    VulnerabilityListResponse,
    VulnerabilityPriorityChangeResponse,
    VulnerabilityQualityGateResponse,
    VulnerabilityReopenResponse,
    VulnerabilityResolveResponse,
    VulnerabilityStatusChangeResponse,
    VulnerabilitySummary,
    VulnerabilityUnassignResponse,
    Webhook,
    WebhookCreateResponse,
    WebhookDeleteResponse,
    WebhookListResponse,
)

__version__ = PACKAGE_VERSION

__all__ = [
    # Clients
    "Rank",
    "AsyncRank",
    # Exceptions
    "RankError",
    "APIError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "ConflictError",
    "UnprocessableEntityError",
    "RateLimitError",
    "InternalServerError",
    "APIConnectionError",
    "APITimeoutError",
    # Streaming
    "Stream",
    "AsyncStream",
    "ServerSentEvent",
    # Utilities
    "NOT_GIVEN",
    # Shared types
    "RankModel",
    "PaginatedResponse",
    "PaginationMeta",
    "PaginationInfo",
    "Permission",
    "MessageResponse",
    "SuccessResponse",
    "ErrorDetail",
    # Auth types
    "User",
    "Tier",
    "Trial",
    "Subscription",
    "UserTeam",
    "UserTeamRole",
    "Session",
    "SessionListResponse",
    "SessionUserData",
    "ApiToken",
    "ApiTokenTeam",
    "AvailableTeam",
    "ApiTokenLimits",
    "ApiTokenListResponse",
    "ApiTokenCreateResponse",
    "AvailablePermissionsResponse",
    "ProfileUpdateResponse",
    "UpdateEmailResponse",
    "UpdateUsernameResponse",
    # Pentest types
    "Pentester",
    "PentestTeam",
    "PentestAsset",
    "RiskScore",
    "Pentest",
    "PentestListResponse",
    "FinishVulnSummary",
    "PentestFinishResponse",
    "QualityGateFailure",
    "QualityGatePentestResult",
    "QualityGateResponse",
    "AssetListResponse",
    "AssetCreateResponse",
    "PentestComment",
    "PentestCommentListResponse",
    "PentestCommentCreateResponse",
    "Webhook",
    "WebhookListResponse",
    "WebhookCreateResponse",
    "WebhookDeleteResponse",
    "PentestAgent",
    "PentestAgentListResponse",
    "AgentAssignment",
    "AssignAgentsResponse",
    "UnassignAgentResponse",
    "DeactivateAgentsResponse",
    "DefaultAgentPhase",
    "DefaultAgentsResponse",
    "OperationEvidenceVuln",
    "OperationEvidence",
    "EvidencesResponse",
    "VulnerabilityEvidenceResponse",
    "EvidenceFile",
    "EvidenceFileListResponse",
    "EvidenceFileUploadResponse",
    "EvidenceFileDeleteResponse",
    "Vulnerability",
    "VulnerabilityListItem",
    "VulnerabilityListResponse",
    "VulnerabilitySummary",
    "VulnerabilityExportResponse",
    "VulnerabilityQualityGateResponse",
    "VulnerabilityResolveResponse",
    "VulnerabilityReopenResponse",
    "VulnerabilityFalsePositiveResponse",
    "VulnerabilityAcceptRiskResponse",
    "VulnerabilityStatusChangeResponse",
    "VulnerabilityPriorityChangeResponse",
    "VulnerabilityAssignResponse",
    "VulnerabilityUnassignResponse",
    "BulkStatusError",
    "BulkStatusResponse",
    "VulnerabilityComment",
    "VulnerabilityCommentListResponse",
    "VulnerabilityCommentCreateResponse",
    "VulnerabilityCommentUpdateResponse",
    "VulnerabilityCommentDeleteResponse",
    "VulnerabilityHistoryItem",
    "VulnerabilityHistoryResponse",
    "PentestCancelResponse",
    "ProcessedVulnerability",
    "ProcessVulnerabilitiesResponse",
    "GenerateReportResponse",
    # Version
    "__version__",
]
